### ISSUE TITLE
Connect 4, working on win logics 

### ISSUE THREAD

**Issue by mariawhen** [mariawhen/ConnectFour#1]
Have win logic for vertical wins for Player 2 ONLY so far.. 

Trying to create a global declareWinner..

**Comment by jim-clark** [comment]
- Your code that *checks for a winner* should most definitely be reusable for either player.

- Note that you should only have to check if the player that just made a move is the winner.  In other words, you don't have to check if both players won the game after a player moves, just the one that made the move.

**Comment by h4w5** [comment]
Please resubmit using the correct structure outlined in the [issues protocol](https://github.com/ga-students/WDI_DTLA_4/tree/master/projects/project_issues_protocol).
