### ISSUE TITLE
Reset Function

### ISSUE THREAD

**Issue by mariawhen** [mariawhen/ConnectFour#2]
Can't get board to reset after a win

**Comment by jim-clark** [comment]
Should be very similar to the way you **initialized** your game board when the app loads.  If you don't have one already, it makes sense to put your initialization code in its own function that you can call any time necessary (when the page loads, when a player clicks a *Start* button, etc.).

**Comment by h4w5** [comment]
Please resubmit using the correct structure outlined in the [issues protocol](https://github.com/ga-students/WDI_DTLA_4/tree/master/projects/project_issues_protocol).

**Comment by mariawhen** [comment]
Thank you!
